/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import java.awt.CardLayout;

/**
 *
 * @author Usuario
 */
public class frmprincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmprincipal
     */
    public frmprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelmenu = new javax.swing.JPanel();
        btncliente = new javax.swing.JButton();
        btnhistorial = new javax.swing.JButton();
        btnprecio = new javax.swing.JButton();
        panelcentral = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("®UTMACHALA-Desarollado por: Dominique Guaycha ");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_END);

        panelmenu.setBackground(new java.awt.Color(255, 0, 255));
        panelmenu.setPreferredSize(new java.awt.Dimension(200, 200));
        panelmenu.setRequestFocusEnabled(false);

        btncliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton2.png"))); // NOI18N
        btncliente.setText("Clientes");
        btncliente.setBorder(null);
        btncliente.setContentAreaFilled(false);
        btncliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclienteActionPerformed(evt);
            }
        });

        btnhistorial.setBackground(new java.awt.Color(255, 153, 153));
        btnhistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton2.png"))); // NOI18N
        btnhistorial.setText("Historial");
        btnhistorial.setBorder(null);
        btnhistorial.setContentAreaFilled(false);
        btnhistorial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhistorialActionPerformed(evt);
            }
        });

        btnprecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton2.png"))); // NOI18N
        btnprecio.setText("Precio ");
        btnprecio.setBorder(null);
        btnprecio.setContentAreaFilled(false);
        btnprecio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelmenuLayout = new javax.swing.GroupLayout(panelmenu);
        panelmenu.setLayout(panelmenuLayout);
        panelmenuLayout.setHorizontalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnprecio)
                    .addComponent(btnhistorial)
                    .addComponent(btncliente))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelmenuLayout.setVerticalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btncliente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnhistorial)
                .addGap(77, 77, 77)
                .addComponent(btnprecio)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        getContentPane().add(panelmenu, java.awt.BorderLayout.LINE_START);

        panelcentral.setBackground(new java.awt.Color(255, 0, 255));
        panelcentral.setLayout(new java.awt.CardLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo.png"))); // NOI18N
        panelcentral.add(jLabel3, "card2");

        getContentPane().add(panelcentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclienteActionPerformed
        panelcentral.add(new panelCliente(), "Clientes");
        try {
            CardLayout cl = (CardLayout) (panelcentral.getLayout());
            cl.show(panelcentral, "Clientes");

        } catch (Exception ex) {
        }
        panelcentral.repaint();
    }//GEN-LAST:event_btnclienteActionPerformed

    private void btnhistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhistorialActionPerformed
        panelcentral.add(new panelHistorial(), "Historial");
        try {
            CardLayout cl = (CardLayout) (panelcentral.getLayout());
            cl.show(panelcentral, "Historial");

        } catch (Exception ex) {
        }
        panelcentral.repaint();
    }//GEN-LAST:event_btnhistorialActionPerformed

    private void btnprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprecioActionPerformed
        panelcentral.add(new panelPrecio(), "Precio");
        try {
            CardLayout cl = (CardLayout) (panelcentral.getLayout());
            cl.show(panelcentral, "Precio");

        } catch (Exception ex) {
        }
        panelcentral.repaint();
    }//GEN-LAST:event_btnprecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncliente;
    private javax.swing.JButton btnhistorial;
    private javax.swing.JButton btnprecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelcentral;
    private javax.swing.JPanel panelmenu;
    // End of variables declaration//GEN-END:variables
}
